#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the package script
npm run package

# Check if there are changes
if [ -n "$(git status --porcelain)" ]; then
    # Add all changes
    git add .
    # Commit with a descriptive message
    git commit -m "chore: update packaged files [automated]"
fi
